### PR TITLE
First draft of idioms

### PR DESCRIPTION
**Pull request by milancurcic**
Here's a first draft, mostly incomplete, but should give an idea of where it's going.

I think the indexing and slicing will be the most important to get right. If we can get that working with the usual Xarray syntax, no matter what the internal implementation is (Awkward Array or otherwise), the higher-level idioms (such as the ones from the EarthCube notebook) should fall into place.

### CODE REVIEW

**Review by selipot — APPROVED** [review]
Great start, I modified a couple of things. Let's merge if @philippemiron has no strong objection.

**Comment by milancurcic** [comment]
Sounds good, thanks.

Is the `obs` (observations) thing a convention or a common term? I've found it weird, personally. Is there an oceanographic Lagrangian use case where `obs` is not `time`?

**Comment by selipot** [comment]
I don't know if it's a convention but that is what we've been using at the GDP and within this project. And this is what Ocean Parcels return for dimensions (trajectory and obs). This allows one to have a `time` variable (a natural name) that have dimensions trajectory (or traj) and obs and that may have specific units (seconds or days with respect to a pivot date). So in conclusion I think that this is what we should use.

**Comment by milancurcic** [comment]
OK, that makes sense. I forgot that the `time` is reserved for the variable name considering the current ragged array limitations.

**Comment by milancurcic** [comment]
Another question that came up for me while writing this, but doesn't have to be addressed immediately:

Is there a use case for a trajectory dimension to be selected by label?

To illustrate what I mean, it's obvious that for N trajectories we can index each by integer 0, 1, 2, ... N-1.

However, should we expect that trajectories could have non-integer labels (e.g. IDs), for example "alpha1", "alpha2", "alpha3", "beta1", etc., so you could do `ds.lon.sel(trajectory='alpha3')`? It seems to me like this would be useful, but I don't have sufficient experience with various datasets.

**Comment by selipot** [comment]
If I understand correctly what you mean by label, yes, we need to be able to select trajectories by metadata variable. To take the example of the GDP: Manufacturer, Buoy Type, Transmission type, etc. So currently by any variable in `gdp_v2.00` or `gdp_6h` in the aws s3 bucket that has dimension `traj`.

**Comment by milancurcic** [comment]
Sounds good, I agree. I'll merge at day-end and we can iterate in follow-up PRs.

**Pull request merged**
